development:
  adapter: mysql2
  database: twistory_db
  pool: 5
  timeout: 5000
  username: 
  password: 

test:
  adapter: mysql2
  database: twistory_db
  pool: 5
  timeout: 5000
  username: 
  password: 

production:
  adapter: mysql2
  database: twistory_db
  pool: 5
  timeout: 5000
  username: 
  password: 
